

services:
  # 1. MySQL Database
  mysqldb:
    image: mysql:8.0
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: productdb
    ports:
      - "3307:3306" # Map host 3307 to container 3306 (avoid conflict if you have local mysql)
    volumes:
      - mysql_data:/var/lib/mysql

  # 2. MongoDB
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # 3. Product Service (Java)
  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    environment:
      # Overwrite application.properties settings here!
      # host 'mysqldb' matches the service name defined above
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/productdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  # 4. Order Service (Java)
  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    environment:
      # SPRING_PROFILES_ACTIVE: docker
      # host 'mongodb' matches the service name above
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/orderdb

  # 5. Frontend (React)
  frontend:
    build: ./frontend-app
    container_name: frontend
    ports:
      - "3000:80" # Map Host 3000 to Container 80 (Nginx)
    depends_on:
      - product-service

volumes:
  mysql_data:
  mongo_data: