name: frontend Service CI/CD

# Trigger: Run this pipeline when code is pushed to 'main'
# AND only if files inside 'product-service' folder changed.
on:
  push:
    branches: [ "main" ]
    paths:
      - 'frontend-app/**'
      - '.github/workflows/frontend-pipeline.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest # Run on a GitHub-hosted Linux server

    steps:
    # 1. Download code
    - name: Checkout Code
      uses: actions/checkout@v4

    # 2. Set up Java 21
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    # 3. Build JAR (Skip tests for now to avoid DB connection errors in CI)
    #- name: Build with Maven
      #run: mvn -B package --file frontend-service/pom.xml -DskipTests

    # 4. Log in to Docker Hub (Uses the Secrets you set up)
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 5. Build Docker Image and Push
    - name: Build and Push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend-app
        push: true
        # Change 'yourusername' below to your actual Docker Hub username!
        # We use ${{ github.run_number }} to create a unique version every time
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/frontend-app:latest
          ${{ secrets.DOCKER_USERNAME }}/frontend-app:v${{ github.run_number }}