name: Frontend Service CI/CD

on:
  push:
    branches: [ "main" ]
    paths:
      - 'frontend-app/**'
      - '.github/workflows/frontend-pipeline.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # 1. Download code
    - name: Checkout Code
      uses: actions/checkout@v4

    # (Optional) If you wanted to run 'npm test' before building Docker, 
    # you would add 'Set up Node.js' here. 
    # Since we are just building the Docker image directly, we skip it.

    # 2. Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 3. Build Docker Image and Push
    - name: Build and Push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend-app
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/frontend-app:latest
          ${{ secrets.DOCKER_USERNAME }}/frontend-app:v${{ github.run_number }}